//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaTredaCrud.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class producto
    {
        public int SKU { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
        public decimal valor { get; set; }
        public Nullable<int> id_tienda { get; set; }
        public string imagen { get; set; }
    
        public virtual tienda tienda { get; set; }
    }
}
